config/routes.rb
Rails.application.routes.draw do

  get '/', to: 'main_menu#index', as: 'home'
  get '/main_menu', to: 'main_menu#index', as: 'menu'
  get '/cards', to: 'cards#index', as: 'cards'
  get '/rules', to: 'rules#index', as: 'how_to_play'
  get '/leaderboards', to: 'leaderboards#index', as: 'leaderboard'
  root "welcome#index"

  resources :users, only: [:new, :create]

  resources :games

  resources :sessions, only: [:new, :create] do
    delete :destroy, on: :collection
  end

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/user.rb
class User < ApplicationRecord
  has_secure_password
  # has_many :posts, dependent: :nullify

  validates :first_name, presence: true
  validates :last_name, presence: true

  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-]+(\.[a-z\d\-]+)*\.[a-z]+\z/i
  validates :email, presence: true,
                    uniqueness: { case_sensitive: false },
                    format: VALID_EMAIL_REGEX

  before_validation :downcase_email


  def full_name
    "#{first_name} #{last_name}"
  end


  private

  def downcase_email
    self.email&.downcase!
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  def authenticate_user!
    redirect_to new_session_path, notice: "Please sign in" unless user_signed_in?
  end

  def user_signed_in?
    current_user.present?
  end
  
  helper_method :user_signed_in?

  def current_user
    @current_user ||= User.find_by_id session[:user_id]
  end
  helper_method :current_user
end

app/controllers/cards_controller.rb
class CardsController < ApplicationController
  def index
  end
end

app/controllers/games_controller.rb
class GamesController < ApplicationController
end

app/controllers/leaderboards_controller.rb
class LeaderboardsController < ApplicationController
  def index
  end
end

app/controllers/main_menu_controller.rb
class MainMenuController < ApplicationController
  def index
  end
end

app/controllers/rules_controller.rb
class RulesController < ApplicationController
  def index
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

  def new
  end

  def create
   @user = User.find_by_email params[:email]
   if @user && @user.authenticate(params[:password])
     session[:user_id] = @user.id
     redirect_to menu_path
   else
     flash[:alert] = "Wrong email or password"
     render :new
   end
 end

 def destroy
    session[:user_id] = nil
    redirect_to root_path, notice: "Logged out!"
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
   @user = User.new
  end

  def create
   @user = User.new user_params
   if @user.save
     session[:user_id] = @user.id
     redirect_to menu_path
   else
     render :new
   end
  end

  private

  def user_params
   params.require(:user).permit(:first_name, :last_name, :email, :user_name,
                                             :password, :password_confirmation)
  end

end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/cards_helper.rb
module CardsHelper
end

app/helpers/games_helper.rb
module GamesHelper
end

app/helpers/leaderboards_helper.rb
module LeaderboardsHelper
end

app/helpers/main_menu_helper.rb
module MainMenuHelper
end

app/helpers/rules_helper.rb
module RulesHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/cards/index.html.erb
<%= link_to "Back", menu_path , class: "btn btn-warning login-btn pull-right" %>
<div id="cards-page">
  <h1 id='card-list-title'>Card List</h1>
    <div id="card-list">
  </div>
</div>

<script type="text/javascript">
//==========================CREATE CARD LIST=========================================
//===================================================================================
const cardList = p1Deck.map(a => Object.assign({}, a));

createList();

function createList(){
    let cardListDiv = document.getElementById("card-list");

    for(let i = 0 ; i < cardList.length - 1 ; i++) {
    let card = cardList[i];
    let cardId = card.cardId;
    //create elements
    let newCard = document.createElement("div");
    let newCardImgContainer = document.createElement("div");
    let newCardImg = document.createElement("IMG");
    let newCardFront = document.createElement("div");
    let newCardSpecialContainer = document.createElement("p");
    let newCardSpecial = document.createTextNode(`${card.special}`);
    let newCardAtkAndHpBox = document.createElement("p");
    let newCardAtkBox = document.createElement("span");
    let newCardAtkBoxSeparator = document.createTextNode('/');
    let newCardHpBox = document.createElement("span");
    let atkBoxAttack = document.createTextNode(`${card.attack}`);
    let atkBoxHealth = document.createTextNode(`${card.health}`);
    let newCardNameContainer = document.createElement("p");
    let newCardName = document.createTextNode(`${card.name}`);
    //add Id and/or className to elements
    newCard.setAttribute("id", "");
    newCard.className = "card-front enlarge pull-right";
    newCardImgContainer.className = "card-img-holder";
    newCardImg.className = "card-img";
    newCardImg.setAttribute("src", card.image);
    newCardFront.className = "card-front-background";
    newCardSpecialContainer.className = "card-special-container";
    newCardSpecial.className = "card-special";
    newCardAtkAndHpBox.className = "atk-hp-box";
    newCardAtkBox.className = "atk-box";
    newCardHpBox.className = "hp-box";
    newCardNameContainer.className = "card-name-container";
    newCardName.className = "card-name";
    // append elements to eachother
    newCard.append(newCardImgContainer);
    newCardImgContainer.append(newCardImg);
    newCard.append(newCardFront);
    newCardFront.append(newCardSpecialContainer);
    newCardSpecialContainer.append(newCardSpecial);
    newCardSpecialContainer.append(newCardAtkAndHpBox);
    newCardAtkAndHpBox.append(newCardAtkBox);
    newCardAtkBox.append(atkBoxAttack);
    newCardAtkAndHpBox.append(newCardAtkBoxSeparator);
    newCardAtkAndHpBox.append(newCardHpBox);
    newCardHpBox.append(atkBoxHealth);
    newCardFront.append(newCardNameContainer);
    newCardNameContainer.append(newCardName);
    //put card in the list
    newCard.style.margin = "10px";

    document.getElementById('card-list').appendChild(newCard);
  }
}
</script>

app/views/games/index.html.erb
<div id="game-page">
  <div id="player2-field">
    <div class="name-container" id="p2-name-container">
      <div class="hexagon" id="p2avatar">
        <div class="hexTop"></div>
        <div class="hexBottom"></div>
      </div>
      <h1 id="p2-name">TK-421</h1>
    </div>
      <div id="p2-deck">
        <ul class="deck" id="p2-add-new-card">
          <li><div class="card-back-deck"></div></li>
          <li><div class="card-back-deck"></div></li>
          <li><div class="card-back-deck"></div></li>
          <li><div class="card-back-deck"></div></li>
          <li><div class="card-back-deck"></div></li>
          <li><div class="card-back-deck"></div></li>
          <li><div class="card-back-deck"></div></li>
          <li><div class="card-back-deck"></div></li>
          <li><div class="card-back-deck"></div></li>
          <li><div class="card-back-deck"></div></li>
        </ul>
      </div>
      <div class='hand-container'>
        <ul id="p2-hand">
        </ul>
      </div>
      <div class="bench-container" id="p2-bench-container">
        <ul class="bench">
          <li class="p2-bench-marker card-marker" id="p2-bench-1"></li>
          <li class="p2-bench-marker card-marker" id="p2-bench-2"></li>
          <li class="p2-bench-marker card-marker" id="p2-bench-3"></li>
          <li class="p2-bench-marker card-marker" id="p2-bench-4"></li>
        </ul>
      </div>
      <div class="active-card-marker card-marker" id ="p2-active-card">
    </div>
  </div>

  <div id="opponent-turn"><p>Opponent's Turn</p></div>

                               <!--PLAYER 2 ☝️ -->

                              <!-- PLAYER 1 👇  -->

  <div id="your-turn"><p>Your Turn</p></div>

      <div id="player1-field">

          <div class="active-card-marker card-marker droppable" id ="p1-active-card"
          ondrop="drop(event)" ondragover="ignoreEvent(event)" ondragleave="dragleave(event)">
        </div>
        <div class="bench-container">
          <ul class="bench">
            <li class="p1-bench-marker card-marker droppable" id="p1-bench-1"
            ondrop="drop(event)" ondragover="ignoreEvent(event)" ondragleave="dragleave(event)"></li>
            <li class="p1-bench-marker card-marker droppable" id="p1-bench-2"
            ondrop="drop(event)" ondragover="ignoreEvent(event)" ondragleave="dragleave(event)"></li>
            <li class="p1-bench-marker card-marker droppable" id="p1-bench-3"
            ondrop="drop(event)" ondragover="ignoreEvent(event)" ondragleave="dragleave(event)"></li>
            <li class="p1-bench-marker card-marker droppable" id="p1-bench-4"
            ondrop="drop(event)" ondragover="ignoreEvent(event)" ondragleave="dragleave(event)"></li>
          </ul>
        </div>
        <div class='hand-container'>
          <ul id="p1-hand">
          </ul>
        </div>

        <div id="p1-menu">
          <div id="p1-buttons-container">
              <button type="button" onclick="attack()" class="btn btn-warning btn-sm" id="p1-attack-button">Attack</button>
              <button type="button" onclick="specialAttack()" class="btn btn-warning btn-sm" id="p1-special-button">Special</button>
              <button type="button" onclick="endTurn()" class="btn btn-warning btn-sm"  id="p1-end-turn-button">End Turn</button>
            </div>
            <div class="name-container">
              <div class="hexagon" id="p1avatar">
                <div class="hexTop"></div>
                <div class="hexBottom"></div>
              </div>
              <h1 id="p1-name">Meeseeks</h1>
            </div>
        </div>
        <div class=""id="p1-deck">
          <ul class="deck" id="p1-add-new-card">
            <li><div class="card-back-deck"></div></li>
            <li><div class="card-back-deck"></div></li>
            <li><div class="card-back-deck"></div></li>
            <li><div class="card-back-deck"></div></li>
            <li><div class="card-back-deck"></div></li>
            <li><div class="card-back-deck"></div></li>
            <li><div class="card-back-deck"></div></li>
            <li><div class="card-back-deck"></div></li>
            <li><div class="card-back-deck"></div></li>
            <li><div class="card-back-deck"></div></li>
          </ul>
        </div>

    </div>

      <div id="cloned-card-holder"></div>

      <div id="speech-bubble-container">
        <p class="bubble" id="speech-bubble"></p>
      </div>
      <div id="heads-or-tails">
        <button type="button" onclick="headsSelected()" class="btn btn-warning btn-lg h-or-t-btns">Heads</button>
        <h1>Or</h1>
        <button type="button" onclick="tailsSelected()" class="btn btn-warning btn-lg h-or-t-btns">Tails</button>
      </div>

      <%= image_tag('eyes.png', id: "eyes") %>
      <%= image_tag("explosionbasic.png", id: "p1-explosion") %>
      <%= image_tag("ribbon-winner.png", id: "you-win") %>
      <%= image_tag("ribbon-loser.png", id: "you-lose") %>
      <%= image_tag("explosionbasic.png", id: "p2-explosion") %>
       <div id="coin-container">
         <div id="coin-img">
           <div id="coin-img-front"></div>
           <div id="coin-img-back"></div>
       </div>
     </div>
  </div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>DoggoFighter</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all' %>
    <%= javascript_include_tag 'application' %>
  </head>

    <%= yield %>

</html>

app/views/leaderboards/index.html.erb
<div class="sign-in-page">
  <%= link_to "Back", menu_path , class: "btn btn-warning login-btn pull-right" %>
  <div id="leader-board-container">
    <h1 id="leaderboard-header">LEADERBOARD</h1>
    <br>
    <table>
      <tr>
        <th>User Name</th>
        <th>WINS</th>
        <th>LOSES</th>
      </tr>
      <tr>
        <td>DoggoMasterSteve</td>
        <td>2312678</td>
        <td>0</td>
      </tr>
      <tr>
        <td>CanIAskYouAQuestion</td>
        <td>6211</td>
        <td>5012</td>
      </tr>
      <tr>
        <td>OhBaby</td>
        <td>6205</td>
        <td>5122</td>
      </tr>
      <tr>
        <td>PewPewMasta</td>
        <td>5906</td>
        <td>4832</td>
      </tr>
      <tr>
        <td>Slim</td>
        <td>5820</td>
        <td>4241</td>
      </tr>
      <tr>
        <td>WooF</td>
        <td>5818</td>
        <td>3900</td>
      </tr>
      <tr>
        <td>ThatGuy</td>
        <td>5725</td>
        <td>4120</td>
      </tr>
      <tr>
        <td>CatsAreBetter</td>
        <td>5689</td>
        <td>5123</td>
      </tr>
      <tr>
        <td>FrankdaTank</td>
        <td>5637</td>
        <td>5098</td>
      </tr>
      <tr>
        <td>YourNameGoesHere</td>
        <td>5581</td>
        <td>3259</td>
      </tr>
      <tr>
        <td>NurfHerder</td>
        <td>5517</td>
        <td>3212</td>
      </tr>
      <tr>
        <td>Hizmata</td>
        <td>5502</td>
        <td>4501</td>
      </tr>
      <tr>
        <td>ElTrolloLoco</td>
        <td>5492</td>
        <td>4921</td>
      </tr>
      <tr>
        <td>SlurpeeFiend</td>
        <td>5424</td>
        <td>2021</td>
      </tr>

    </table>
  </div>
</div>

app/views/main_menu/index.html.erb
<body class="sign-in-page" id="if-signed-in">
  <div class="login-btn-container">
    <% if user_signed_in? %>
    <!-- Hello <%= current_user.full_name %>, -->
    <%= link_to "Start New Game", games_path , class: "btn btn-warning login-btn" %>
    <br>
    <%= link_to "How To Play", how_to_play_path , class: "btn btn-warning login-btn" %>
    <br>
    <%= link_to "Card List", cards_path , class: "btn btn-warning login-btn" %>
    <br>
    <%= link_to "Leader Board", leaderboard_path , class: "btn btn-warning login-btn" %>
    <br>
    <%= link_to "Logout", sessions_path, class: "btn btn-warning login-btn", method: :delete,
    data: {confirm: "Are you sure you want to log out?"}%>
  <% end %>
  </div>
</body>

app/views/rules/index.html.erb
<div class="sign-in-page">
  <%= link_to "Back", menu_path , class: "btn btn-warning login-btn pull-right" %>
  <div id="rules-container">
  <h3>How To Play:</h3>
  <br>
  <strong class="pull-left">Card Types:</strong>
  <br>
  <p>There are two card types in the game, "doggo" and "utility".
  <br>
  <br>
  <strong>Doggo Card:</strong>
  <br><br>
  The Doggo cards are used to attack the opponent's doggo card in order to knock them out of the game.
  Doggo cards have attack and health stats located at the bottom right corner of the card. Each doggo also has a unique special attack show in the center of the card. In order to use a doggos special attack you must first build up bones by attacking the opponents doggo and once your bone bar is full you can release the awesome power of your doggos special ability.
  <br>
  <br>
  <strong>Utility Card:</strong>
  <br>
  <br>
  The utility cards are used to alter the course of the game. Utility cards have no attack value and can only be used once before they are discarded. Each player can use a maximum of two utility cards per round. Some of the actions a utiltiy card can do include buff, heal, draw additional cards or swap an active card with a bench card.
  <br>
  <br>
  <strong>Game Rules:</strong>
  <br>
  <br>
  At the start of the game a coin toss will determain who may attack first. During the first round, the setup round, each player is delt 5 cards. Each player must then place at least one doggo card in the attacking postion and then the player has the option of placing doggo cards into the bench slots, a maximum of 4 bench cards can be in play at any given time. During this round no player will be able to attack. A player may use up to 2 utility cards per turn and attack only once per turn.
  Once the setup round is complete each player will take turns trying to defeat their opponent's doggos. The first player
  to defeat 5 of their opponents doggos will be declared the victor. Do you have what it takes to become the doggo master?
 </p>
</div>
</div>

app/views/users/new.html.erb
<div class="sign-in-page">
<div id="sign-up-background">
  <div id="sign-up-container">
    <h1 id="sign-up-h1">Sign Up</h1>
    <br>
    <div id="sign-up-errors">
    <% if @user.errors.any? %>
      <ul>
        <% @user.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    <% end %>
  </div>

    <%= form_for @user do |f| %>
      <div class="form-group">
        <%= f.label :user_name %>
        <%= f.text_field :user_name, class:"form-control" %>
      </div>
      <div class="form-group">
        <%= f.label :email %>
        <%= f.email_field :email, class:"form-control" %>
      </div>
      <div class="form-group">
        <%= f.label :password %>
        <%= f.password_field :password, class:"form-control" %>
      </div>
      <div class="form-group">
        <%= f.label :password_confirmation %>
        <%= f.password_field :password_confirmation, class:"form-control" %>
      </div>
      <%= submit_tag "Sign Up", class:"btn btn-warning" %>
    <% end %>
  </div>
</div>
</div>

app/views/welcome/index.html.erb
<body class="sign-in-page" id="if-signed-in">
  <div class="login-btn-container">
    <%= link_to "Login", new_session_path , class: "btn btn-warning login-btn" %>
    <br>
    <%= link_to "Sign Up", new_user_path , class: "btn btn-warning login-btn" %>
  </div>
</div>
</body>